# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcc6c8e86742a242dce8199029a83dcf6f7b584cdbeb3eb6beb629033b863bc95a6dbf55fb9d5d82699b2a9b11c1473891a16cd88eec4e4209fcddb9bbc5c88b

test:
  secret_key_base: 1dd851cdfe0f8a651f353c79f2f1c4c34c366eb883088920f669446cf79a61172914da4774c479fefdf3471c6f48a8c50aa1d2aea489a604f228c942408853ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
